apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: llama
  labels:
    type: external
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 11434
      protocol: TCP
  selector:
    app: ollama
